project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Proyectos de Investigación Vigentes -- Facultad de Ciencias Sociales"
  navbar:
    background: "#212121"

format:
  html:
    mainfont: "Montserrat" 
    css: proyectos-listing.css

execute:
  freeze: auto



